### ISSUE TITLE
MSM3 Decoding fails when the number of Signals is not consistent per SV

### ISSUE THREAD

**Issue by jcmb** [semuconsulting/pyrtcm#21]
MSM3 Decoding fails when the number of Signals is not consistent per SV

GPS SV's today are a mix of SV types so they have different signals.  

The Job of DF394 is to indicate the number of SV's in the message.
DF395 indicates what signal may be in the message.
DF396 indicates for a given SV which signals it has. 

For the first 1073 message in the same file these values are 

Message, Number of Bits, Hex and ion Binary

```
DB394 08 430b180000000000 0000010000110000101100011000000000000000000000000000000000000000
DB395 04 40408100                   01000000010000001000000100000000
DB396 20 bbaaccbb00000000 0000000000000000000000000000000010111011101010101100110010111011
```

This shows that we have 8 SV's and there are 4 possible signals for each SV. But there are only 20 Signals in the message.

A pprint of the object returned correctly indicates that some SV's should not have values. DF400_02 for example has a signal type of N/a, which is correct. But there is a value there. 

If you look at the object DF401_16 is the last value that is not zero, this is because we are consuming 32 values in the DF messages, such as DF400, instead of 20 as we should be consuming. I think we are using the size of NCELL, instead of the number of set bits in NCELL to determine if we should be reading data. I can not work out where to fix this in the code :-(

```<RTCM(1073, DF002=1073, DF003=11, GNSSEpoch=84967000, DF393=1, DF409=0, DF001_7=0, DF411=1, DF412=0, DF417=0, DF418=0, DF394=301936338347753472, NSat=8, DF395=1077969152, NSig=4, DF396=3148532923, DF398_01(006)=0.59082031, DF398_02(011)=0.93457031, DF398_03(012)=0.70507812, DF398_04(017)=0.87792969, DF398_05(019)=0.59472656, DF398_06(020)=0.53222656, DF398_07(024)=0.51464844, DF398_08(025)=0.97460938, DF400_01(006,1C)=-0.00019592, DF400_02(006,n/a)=-0.00015676, DF400_03(006,2X)=-0.00015122, DF400_04(006,5X)=-0.00035965, DF400_05(011,1C)=-0.00032997, DF400_06(011,n/a)=-0.00031614, DF400_07(011,2X)=-0.00033778, DF400_08(011,5X)=-0.00030923, DF400_09(012,1C)=-1.365e-05, DF400_10(012,n/a)=3.707e-05, DF400_11(012,2X)=-0.00016618, DF400_12(012,n/a)=-0.0001381, DF400_13(017,1C)=0.00023931, DF400_14(017,n/a)=0.00028312, DF400_15(017,2X)=-0.00020283, DF400_16(017,n/a)=-0.00014156, DF400_17(019,1C)=-0.00013012, DF400_18(019,2W)=-0.0005191, DF400_19(019,n/a)=-0.0004698, DF400_20(019,n/a)=-0.00045782, DF400_21(020,1C)=-6.14e-06, DF400_22(020,2W)=0.00053459, DF400_23(020,n/a)=-0.00074816, DF400_24(020,n/a)=6.771e-05, DF400_25(024,1C)=-0.00085521, DF400_26(024,n/a)=-0.00088722, DF400_27(024,2X)=-5.484e-05, DF400_28(024,5X)=-0.00085467, DF400_29(025,1C)=-0.00048357, DF400_30(025,n/a)=-0.00044096, DF400_31(025,2X)=-0.00037336, DF400_32(025,5X)=5.43e-05, DF401_01(006,1C)=-0.00066015, DF401_02(006,n/a)=-0.00318417, DF401_03(006,2X)=-0.00069398, DF401_04(006,5X)=-0.00061145, DF401_05(011,1C)=-0.00211838, DF401_06(011,n/a)=-3.505e-05, DF401_07(011,2X)=-0.00244984, DF401_08(011,5X)=-0.0009577, DF401_09(012,1C)=-0.00095409, DF401_10(012,n/a)=0.000166, DF401_11(012,2X)=0.00096512, DF401_12(012,n/a)=0.00166887, DF401_13(017,1C)=-0.0, DF401_14(017,n/a)=-0.0, DF401_15(017,2X)=-0.0, DF401_16(017,n/a)=-7.63e-06, DF401_17(019,1C)=0.0, DF401_18(019,2W)=0, DF401_19(019,n/a)=0, DF401_20(019,n/a)=0, DF401_21(020,1C)=0, DF401_22(020,2W)=0, DF401_23(020,n/a)=0, DF401_24(020,n/a)=0, DF401_25(024,1C)=0, DF401_26(024,n/a)=0, DF401_27(024,2X)=0, DF401_28(024,5X)=0, DF401_29(025,1C)=0, DF401_30(025,n/a)=0, DF401_31(025,2X)=0, DF401_32(025,5X)=0, DF402_01(006,1C)=0, DF402_02(006,n/a)=0, DF402_03(006,2X)=0, DF402_04(006,5X)=0, DF402_05(011,1C)=0, DF402_06(011,n/a)=0, DF402_07(011,2X)=0, DF402_08(011,5X)=0, DF402_09(012,1C)=0, DF402_10(012,n/a)=0, DF402_11(012,2X)=0, DF402_12(012,n/a)=0, DF402_13(017,1C)=0, DF402_14(017,n/a)=0, DF402_15(017,2X)=0, DF402_16(017,n/a)=0, DF402_17(019,1C)=0, DF402_18(019,2W)=0, DF402_19(019,n/a)=0, DF402_20(019,n/a)=0, DF402_21(020,1C)=0, DF402_22(020,2W)=0, DF402_23(020,n/a)=0, DF402_24(020,n/a)=0, DF402_25(024,1C)=0, DF402_26(024,n/a)=0, DF402_27(024,2X)=0, DF402_28(024,5X)=0, DF402_29(025,1C)=0, DF402_30(025,n/a)=0, DF402_31(025,2X)=0, DF402_32(025,5X)=0, DF420_01(006,1C)=0, DF420_02(006,n/a)=0, DF420_03(006,2X)=0, DF420_04(006,5X)=0, DF420_05(011,1C)=0, DF420_06(011,n/a)=0, DF420_07(011,2X)=0, DF420_08(011,5X)=0, DF420_09(012,1C)=0, DF420_10(012,n/a)=0, DF420_11(012,2X)=0, DF420_12(012,n/a)=0, DF420_13(017,1C)=0, DF420_14(017,n/a)=0, DF420_15(017,2X)=0, DF420_16(017,n/a)=0, DF420_17(019,1C)=0, DF420_18(019,2W)=0, DF420_19(019,n/a)=0, DF420_20(019,n/a)=0, DF420_21(020,1C)=0, DF420_22(020,2W)=0, DF420_23(020,n/a)=0, DF420_24(020,n/a)=0, DF420_25(024,1C)=0, DF420_26(024,n/a)=0, DF420_27(024,2X)=0, DF420_28(024,5X)=0, DF420_29(025,1C)=0, DF420_30(025,n/a)=0, DF420_31(025,2X)=0, DF420_32(025,5X)=0)>```

The decoding works perfectly with other systems in which every SV has consistent signals. 

This is with 1.0.5 

- A binary / hexadecimal dump of the rtcm data stream (e.g. from PuTTY, screen or u-center).

**To Reproduce**

Steps to reproduce the behaviour:
1. Any GNSS receiver that is capable of GNSS L1/L2/L5 should show this. Sample SPS855.BIN

**Expected Behaviour**

The SVs with a signal of N/A should not have values and the DF420 should have values.

**Desktop (please complete the following information):**

- Mac OS using Python 3.9.6
- File, using rtcmfile.py 

**GNSS/GPS Device (please complete the following information as best you can):**

- Trimble SPS855 and Trimble R750
- 5.60/6.20
- RTCM MSM3
 
**Additional context**
[SPS855.BIN.zip](https://github.com/semuconsulting/pyrtcm/files/11036058/SPS855.BIN.zip)

I have a pull request in for a fix that will raise a parsing error when the amount of data in the packet is exhausted, which helps in showing this problem

**Comment by semuadmin** [comment]
Hi @jcmb Thanks for the report - much appreciated. Fix identified and PR awaiting review.
