### ISSUE TITLE
Message type 4085 implementation?

### ISSUE THREAD

**Issue by Alexgar24** [semuconsulting/pyrtcm#5]
First of all congratulations for the amazing repo, I've checked just a few lines and the code looks really solid.

I would like to ask if you have in mind the implementation of the EDAS property message (RTCM Message Number 4085).

Thanks for the time. :)

**Comment by semuadmin** [comment]
Hi @Alexgar24 Thanks for the kind comments.

The only reason I haven't implemented the proprietary RTCM3 message types (i.e. those in the range 4001-4095) is that their format is not included in the official RTCM 10403.3 specification and the information is not (generally) in the public domain.

According to the offical specification, 4085 is attributed to the European GNSS Supervisory Authority (GSA).
I've checked on the www.gsa.europa.org web site but could find no publicly accessible documentation on the EDAS RTCM3 implementation. You may have more success yourself if you have the time.

If you're able to offer additional insight and/or a link to the specification for the 4085 message, I'm more than happy to implement it. The repo is designed to be easily extensible so also happy to take dictionary updates via PR.

Same goes for the other proprietary messages. 

Sorry I can't be more helpful at this time.

**Comment by semuadmin** [comment]
Hi - I'm going to close this issue for now, but I have a task on the backlog to continue to research sources of proprietary RTCM message formats. In the meantime, contributions very welcome.
