### ISSUE TITLE
RTCM3 message invalid - failed CRC: b'\xcfJ*'

### ISSUE THREAD

**Issue by jaguaryang** [semuconsulting/pyrtcm#61]
I am using the latest version pyrtcm 1.1.2. For some reason, I get a lot of CRC errors, a small number of Header errors, and a small number of parsing successes. It seems that the successful message types are all system messages. Can anyone help me solve this problem?

Unknown protocol header b'\xb5\xdb'.
RTCM3 message invalid - failed CRC: b'\xcfJ*'
RTCM3 message invalid - failed CRC: b'\x95Y-'
RTCM3 message invalid - failed CRC: b'\n66'
RTCM3 message invalid - failed CRC: b'\x82\xd93'
RTCM3 message invalid - failed CRC: b'\x13\xe1t'
RTCM3 message invalid - failed CRC: b'\xe4\x0fe'
RTCM3 message invalid - failed CRC: b'\xcfJ*'
RTCM3 message invalid - failed CRC: b'\xb5Y,'
RTCM3 message invalid - failed CRC: b'\x82\xd9s'
RTCM3 message invalid - failed CRC: b'\x13\xdf|'
RTCM3 message invalid - failed CRC: b'\xe3\xefe'
RTCM3 message invalid - failed CRC: b'\xcbI\xea'
RTCM3 message invalid - failed CRC: b'\x94\xd9,'
Message Type: 1006

**Comment by semuadmin** [comment]
Hi @jaguaryang 

Please use the [Issue Template](https://github.com/semuconsulting/pyrtcm/blob/main/.github/ISSUE_TEMPLATE/bug_report.md) provided and include:

1) The **complete** Python script that you're using to obtain these messages (*it's not possible to provide assistance without this*).
1) The GNSS device you're using.
1) Platform operating system.
1) if possible, a log of the actual binary data you're receiving.

Thanks

**Comment by semuadmin** [comment]
@jaguaryang FYI happy to help, but will close Issue in 3 days if no further information provided.

**Comment by semuadmin** [comment]
Closed due to non-response.
