### ISSUE TITLE
It would be nice if pyrtcm was capable of timing out. You could have a parameter called timeout_sec that corresponds to the seconds the read() function will wait until timing out.

### ISSUE THREAD

**Issue by sandeshworld** [semuconsulting/pyrtcm#9]
I could help implement it if you would like. I noticed in one of your comments you state that timeout should be handled outside of pyrtcm but not sure how to do that since pyrtcm is capturing the socket.

**Comment by semuadmin** [comment]
Hi @sandeshworld

You simply set an appropriate `timeout` parameter when setting up the Serial stream e.g.

` stream = Serial('/dev/tty.usbmodem14101', 9600, timeout=3)`

NB: this is a function of the `Serial` library, not `pyrtcm`.

**Comment by semuadmin** [comment]
Hi @sandeshworld To clarify, are you just talking about reading from sockets?

**Comment by semuadmin** [comment]
Hi @sandeshworld 

Are you happy for me to close this issue now?
